config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]
  
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  mount_uploader :image, ImageUploader
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
  
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_posts = user.posts.count
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :update, :edit]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def new
    @post = Post.new
  end  
  
  def create
    @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿しました。'
      redirect_to root_url
    else
      @posts = current_user.posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = '投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_to root_url
  end
  
  def show
  end
  
  def edit
  end
  
  def update

    if @post.update(post_params)
      flash[:success] = '投稿を編集しました'
      redirect_to @post
    else
      flash.now[:danger] = '正しく編集されませんでした'
      render :edit
    end
  end
  private

  def post_params
    params.require(:post).permit(:content, :title, :image)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
      @posts = Post.all.order(id: :desc).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
     @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">REP.CAM</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <a class="navbar-brand" href="/">トップページ</a>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
        <li class="nav-item"><%= link_to 'ユーザー登録', signup_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=">
    <title>REP.CAM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_posts.html.erb
<div class="container">
　  <div class="row">
      <div class="col">
<ul class="list-unstyled">
  <% posts.each do |post| %>
    <li class="media mb-3">
      <div class="media-body">
        <div>
          <%= link_to post.id, post %> : <span class="text-muted">posted at <%= post.created_at %></span>
        </div>
        <h5>
          <br>
        </h5>
        <div>
          <h4><%= post.title %></h4>
          <h5>
            <br>
          </h5>  
              <%= image_tag post.image.url, :width => '40%', :height => 'auto' %> 
          <h2>
            <br>
          </h2> 
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate posts %>
</ul>
    </div>
  </div>
</div>  

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="center jumbotron">
　<div class="text-center">
  <h1><%= @post.id %> : 投稿詳細ページ</h1>
  </div>
</div>
　<div class="text-center">
      <%= form_with(model: @post, local: true) do |f| %>
        <div class="form-group">
          <%= f.label :title, 'タイトル' %>
          <br>
          <%= f.text_field :title %>
          <br>
          <br>
            <%= f.label :image, '画像投稿' %>
          <br>  
            <%= f.file_field :image %>
            <%= f.hidden_field :image_cache %>
          <br>
          <br>
          <%= f.label :content, '投稿説明' %>
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit '更新', class: 'btn btn-primary' %>
    <% end %>  

    <h1>
      <br>
      <br>
    </h1>
    <%= link_to 'マイページに戻る', user_path(current_user) %>
    <h1>
      <br>
      <br>
    </h1>
  </div>  

app/views/posts/new.html.erb
<div class="center jumbotron">
　<div class="text-center">
  <h1>新規投稿ページ</h1>
  </div>
</div>
　<div class="text-center">
      <%= form_with(model: @post, local: true) do |f| %>
        <div class="form-group">
          <%= f.label :title, 'タイトル' %>
          <br>
          <%= f.text_field :title %>
          <br>
          <br>
            <%= f.label :image, '画像投稿' %>
          <br>  
            <%= f.file_field :image %>
            <%= f.hidden_field :image_cache %>
          <br>
          <br>
          <%= f.label :content, '投稿説明' %>
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>  

    <h1>
      <br>
      <br>
    </h1>    
      <%= link_to 'トップページに戻る', root_path(current_user) %>
    <h1>
      <br>
      <br>
    </h1>
  </div>  

app/views/posts/show.html.erb
<div class="center jumbotron">
　<div class="text-center">
  <h1><%= @post.id %> : 投稿詳細ページ</h1>
  </div>
</div>
<div class="text-center">
  <h1>
    <br>
    <br>
  </h1>
  <h4>タイトル</h4>
  <h1>
    <br>
  </h1>
  <h3><%= @post.title %></h3>
  <h1>
    <br>
    <br>
  </h1>
    <%= image_tag @post.image.url, :width => '80%', :height => 'auto' %>
  <h1>
    <br>
    <br>
  </h1>
  <h4>投稿説明</h4>
  <h1>
    <br>
  </h1>
  <h3><%= @post.content %></h3>
  <br>
  <h1>
    <br>
      <div>
          <% if current_user == @post.user %>
            <%= link_to '編集する', edit_post_path(@post), class: 'btn btn-secondary' %>
            <%= link_to "削除する", @post, method: :delete, data: { confirm: "本当に削除してよろしいですか？" }, class: 'btn btn-danger' %>
          <% end %>
      </div>
    <br>
    <br>
  </h1>
  <%= link_to 'マイページに戻る', user_path(current_user) %>
  <h1>
    <br>
    <br>
    <br>
  </h1>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>

　
    <%= image_tag "REP.CAM.jpg", alt:"" , id:"assets", class: "image", width: "100%" %>
  
  <h1>
      <br>
      <br>
  </h1>
  <div class="text-center">
   <%= link_to '新規投稿する', new_post_path, class: 'btn btn-lg btn-primary' %>
  <h1>
    <br>
    <br>
  </h1>        
  <h1>投稿一覧</h1>
  <h3>
    <br>
    <br>
  </h3>
<div class="container">
  <div class="center jumbotron">
　  <div class="row">
      <div class="col">
        <%= render 'posts/posts', posts: @posts %>
      </div>
    </div>
  </div>  
</div>
<% else %>
  <div class="img_block">
    <%= image_tag "REP.CAM.jpg", alt:"" , id:"assets", class: "image", width: "100%" %>
  </div>  
  <h1>
      <br>
      <br>
  </h1>
  <div class="text-center">
    <h2>ユーザー登録をして、自慢のキャンプスタイルを投稿しよう！</h2><br>
    <h2>↓　↓　↓　↓</h2>
      <%= link_to 'ユーザー登録', signup_path, class: 'btn btn-lg btn-primary' %>
      <br>
    <br>
  </h1>
  <h2>
    <br>
    <br>
  </h2>
  <h1>投稿一覧</h1>
  <h3>
    <br>
    <br>
  </h3>
  <div class="center jumbotron">
　  <div class="text-center">
      <h4><%= render 'posts/posts', posts: @posts %></h4>
    </div>
  </div>  
  <h3>
    <br>
    <br>
  </h3>
  </div>  
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div style="text-align: center;">
      <%= f.submit '登録', class: 'btn btn-lg btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="center jumbotron">
  <div class="text-center">
    <h1><%= @user.name %>のマイページ</h1>
  </div>　
</div>
  <br>
  <br>

<div class="text-center">
  <%= link_to '新規投稿する', new_post_path, class: 'btn btn-lg btn-primary' %>
  <h1>
  <br>
  <br>
  </h1>
  <h2>MY STYLE一覧</h2>
  <br>
  <br>
  <h4><%= render 'posts/posts', posts: @posts %></h4>
  <h1>
    <br>
  </h1>
  <%= link_to 'トップページに戻る', root_path %>
  <h1>
    <br>
  </h1>
</div>  
  